name: Python Unit Testing and Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  python_ci:

    runs-on: ubuntu-latest
    strategy:
    matrix:
      python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Setup python ${{ matrix.python-version }}

    - name: Install dependencies
      runs: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

    - name: Run tests
      run: |
        python test.py test


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date + %s)
    